version: 0.2

phases:
  install:
    commands:
      - echo Installing...

  build:
    commands:
      - echo Build started

  post_build:
    commands:
      - echo Deploying to S3
      - aws s3 cp . s3://ci-cd-website-ankush --recursive

artifacts:
  files:
    - '**/*'
